export const NOTIFICATION_THEME_SUCCESS = 'NOTIFICATION_THEME_SUCCESS';
export const NOTIFICATION_THEME_FAILURE = 'NOTIFICATION_THEME_FAILURE';
export const NOTIFICATION_THEME_WARNING = 'NOTIFICATION_THEME_WARNING';

export const INPUT_THEME_ERROR = 'INPUT_THEME_ERROR';
